Feature/conversions
fivetran/dbt_reddit_ads pull request #13
Opened 2024-10-14 21:12 UTC by fivetran-reneeli

to be completed

2024-10-15 15:37 UTC, fivetran-reneeli commented
will close out issue #3 as well since this is addressed

2024-10-24 17:24 UTC, fivetran-jamie commented on packages.yml
> +  - git: https://github.com/fivetran/dbt_reddit_ads_source.git
switch

2024-10-24 19:35 UTC, fivetran-joemarkiewicz requested changes
@fivetran-jamie @fivetran-reneeli great job on this PR! @fivetran-jamie there are a few small changes I would like to be addressed before this is ready for release.

2024-10-24 19:35 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +
We don't mention the upstream new staging models here at all or reference the other breaking changes in the source package. Can we make sure to include those here.

2024-10-24 19:35 UTC, fivetran-joemarkiewicz commented on integration_tests/tests/consistency/consistency_account_report.sql
Request to add the conversion metrics to the validation tests but comment them out so they may be added back within a future release and we don't forget about them.

2024-10-24 21:56 UTC, fivetran-joemarkiewicz approved these changes
LGTM

2024-10-24 23:59 UTC, merged